# Tensor Introduction

## Tensorflow
<pre>TensorFlow is a free and open-source software library for machine learning and artificial intelligence. It can be used across a range of tasks but has a particular focus on training and inference of deep neural networks. It was developed by the Google Brain team for Google's internal use in research and production.</pre>

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.14.0'

### Tensors
<pre>Tensors are multi-dimensional arrays with a uniform type (called a dtype). You can see all supported dtypes at tf.dtypes.</pre>

In [9]:
'''
tf.constant() returns a immutable object, while tf.Variable() returns mutable object
'''
scalar=tf.constant(7)
print(scalar)
print(scalar.ndim)

tf.Tensor(7, shape=(), dtype=int32)
0


In [8]:
vector=tf.constant([10,10.0])
print(vector)
vector.ndim

tf.Tensor([10. 10.], shape=(2,), dtype=float32)


1

In [7]:
matrix = tf.constant([[10, 7], [7, 10]])
print(matrix)
matrix.ndim

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)


2

In [10]:
changable=tf.Variable([7,4])
changable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 4])>

### Random Tensors

**Uniform Distribution**<br>
*Uniform distributions are probability distributions with equally likely outcomes. In a discrete uniform distribution, outcomes are discrete and have the same probability.*

In [13]:
# tf.random.uniform(<shape>)
tf.random.uniform([1,2,3])

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[0.6372268 , 0.83273256, 0.7440475 ],
        [0.32472563, 0.24358654, 0.06681085]]], dtype=float32)>

In [14]:
# seeded
gen=tf.random.Generator.from_seed(42)
t1=gen.normal((3,2))
t1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [15]:
t2=gen.normal((3,2))
t2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.17522676,  0.71105534],
       [ 0.54882437,  0.14896014],
       [-0.54757965,  0.61634356]], dtype=float32)>

In [16]:
t3=gen.normal((1,2))
t3

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[ 1.2866228, -0.714756 ]], dtype=float32)>